version: '3.0'

services:
  main:
    container_name: index
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ../node_modules
    ports:
      -9000:9000
    command: npm start
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    restart: always

volumes: 
  pgdata: